name: Deploy to DigitalOcean

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build/test your project here.
      # ...

      - name: Copy files to droplet
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/your/app/directory/on/droplet"

      - name: Restart app on droplet
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/apps/caprover-test
            npm install  # If necessary
            npm run build
            pm2 restart index
